<?php

/**
 * @file
 * Contains custom_entity.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function custom_entity_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the custom_entity module.
    case 'help.page.custom_entity':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('My Awesome Module') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function custom_entity_theme() {
  return [
    'custom_entity' => [
      'template' => 'custom_entity',
      'render element' => 'children',
    ],
  ];
}
