custom_config.admin:
  title: 'Custom config settings'
  description: 'Creates an admin settings page link'
  parent: system.admin_config_development
  route_name: custom_config.admin_settings
  weight: 100
