<?php

/**
 * @file
 * Contains custom_block.module.
 */

//use Drupal\Core\Routing\RouteMatchInterface;

///**
// * Implements hook_help().
// */
//function custom_block_help($route_name, RouteMatchInterface $route_match) {
//  switch ($route_name) {
//    case 'help.page.custom_block':
//      $output = '';
//      $output .= '<h3>' . t('About') . '</h3>';
//      $output .= '<p>' . t('My Awesome Module') . '</p>';
//      return $output;
//
//    default:
//  }
//}

/**
 * Implements hook_theme().
 *
 * @param $existing
 * @param $type
 * @param $theme
 * @param $path
 *
 * @return array
 */
function custom_block_theme($existing, $type, $theme, $path) {
  return [
    'custom_twig' => [
      'variables' => ['time' => NULL, 'color' => NULL],
      'template' => 'new_year',
    ],
  ];
}


/**
 * Implements hook_preprocess_HOOK().
 */
function custom_block_preprocess_custom_twig(&$variables) {
  $variables['#attached']['library'][] = 'custom_block/color-countdown';
}
