<?php

/**
 * @file
 * Contains mytest.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function mytest_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.mytest':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('My first drupal testing') . '</p>';
      return $output;

    default:
  }
}
